version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=