version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
      
