INSERT INTO heros (name, class) VALUES 
    ('Doomfist', 'attack'),
    ('Genji', 'attack'),
    ('McCree', 'attack'),
    ('Pharah', 'attack'),
    ('Reaper', 'attack'),
    ('Soldier: 76', 'attack'),
    ('Sombra', 'attack'),
    ('Tracer', 'attack'),
    ('Bastion', 'defense'),
    ('Hanzo', 'defense'),
    ('Junkrat', 'defense'),
    ('Mei', 'defense'),
    ('Torbjorn', 'defense'),
    ('Widowmaker', 'defense'),
    ('D.Va', 'tank'),
    ('Orisa', 'tank'),
    ('Reinhardt', 'tank'),
    ('Roadhog', 'tank'),
    ('Winston', 'tank'),
    ('Zarya', 'tank'),
    ('Ana', 'support'),
    ('Lucio', 'support'),
    ('Mercy', 'support'),
    ('Moira', 'support'),
    ('Symmetra', 'support'),
    ('Zenyatta', 'support')
    ;