// Code generated by "stringer -type=GameType"; DO NOT EDIT.

package models

import "fmt"

const _GameType_name = "EscortAssaultHybridControl"

var _GameType_index = [...]uint8{0, 6, 13, 19, 26}

func (i GameType) String() string {
	if i >= GameType(len(_GameType_index)-1) {
		return fmt.Sprintf("GameType(%d)", i)
	}
	return _GameType_name[_GameType_index[i]:_GameType_index[i+1]]
}
