// Code generated by "stringer -type=HeroClass"; DO NOT EDIT.

package models

import "fmt"

const _HeroClass_name = "AttackDefenseTankSupport"

var _HeroClass_index = [...]uint8{0, 6, 13, 17, 24}

func (i HeroClass) String() string {
	if i >= HeroClass(len(_HeroClass_index)-1) {
		return fmt.Sprintf("HeroClass(%d)", i)
	}
	return _HeroClass_name[_HeroClass_index[i]:_HeroClass_index[i+1]]
}
